### ISSUE TITLE
Custom Metrics Missing

### ISSUE THREAD

**Issue by dustman9000** [openshift/operator-custom-metrics#30]
It seems custom metrics are missing with `v0.3.0` when running a simple curl to the metrics server. 

Follow https://github.com/openshift/operator-custom-metrics/blob/master/example/example.go

Then curl: 
`kubectl run -it --rm debug --image=radial/busyboxplus:curl --restart=Never -- curl http://<POD IP>:8080/metrics`

Look for `myapp_processed_ops_total`

**Comment by fahlmant** [comment]
ListenAndServe isn't erroring if the port + path is already bound: https://github.com/openshift/operator-custom-metrics/blob/8e508c67dfed34dbd7e35c3faccae3c74eba9aba/pkg/metrics/metrics.go#L35

Turns out controller-runtime via the operator-sdk claims port 8080 and /metrics, so if this code tries to claim it as well, the code above will silently fail.

**Comment by fahlmant** [comment]
Fixed with v0.4.0
